version: "3.9"
services:
  api:
    image: trading_api:latest
    container_name: trading_api
    networks:
      - api_network
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
  tests:
    image: tests_api:latest
    container_name: api_test
    depends_on:
      - api
    networks:
      - api_network
networks:
  api_network:
volumes:
  app_log:
