name: Control Push
on: push
jobs:
  qa:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8
          pip install -r requirements.txt

      - name: Run tests
        env:
          PANTHER_CHROME_ARGUMENTS: "--disable-dev-shm-usage"
          PANTHER_CHROME_DRIVER_BINARY: "/usr/bin/chromedriver"
          PANTHER_NO_SANDBOX: "1"
        run: |
          pytest tests/domain/

      - name: Run flake8
        uses: py-actions/flake8@v2
