name: Control Push
on: push
jobs:
  qa:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"

      - name: Install pytest and necessary libraries
        run: |
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/domain/

      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          ignore: |
            "E501"
            "E251"
            "W292"
          path: "tests"

      name: Tests API
        runs-on: ubuntu-latest
        steps:
          - name: Checkout on master
            uses: actions/checkout@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Build api image
            run: docker image build -f api.Dockerfile . -t trading_api

          - name: Build tests image
            run: docker image build -f tests.Dockerfile . -t api_tests

          - name: Tests
            run: ./start.sh
        
