name: Control Push
on: push
jobs:
  qa:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8
          pip install -r requirements.txt

      - name: Run tests
        env:
          CHROMEWEBDRIVER: "usr/local/share/chrome_driver/chromedriver"
        run: |
          pytest tests/domain/

      - name: Run flake8
        uses: py-actions/flake8@v2
